{
 "title": "Статистика рекламодателей",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "advertiser_id",
    "label": "ID рекламодателя",
    "query": {
     "query": "label_values(advertiser_daily_clicks_count,advertiser_id)"
    }
   },
   {
    "name": "advertiser_name",
    "query": {
     "query": "label_values(advertiser_total_clicks_count{advertiser_id=\"$advertiser_id\"},advertiser_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Статистика рекламодателя $advertiser_name",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Количество просмотров",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertiser_total_impressions_count{advertiser_id='$advertiser_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество кликов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertiser_total_clicks_count{advertiser_id=\"$advertiser_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Конверсия",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertiser_total_conversion{advertiser_id='$advertiser_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено на клики",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertiser_total_spent_clicks{advertiser_id='$advertiser_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено на просмотры",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertiser_total_spent_impressions{advertiser_id='$advertiser_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Всего потрачено",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertiser_total_spent{advertiser_id='$advertiser_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество просмотров рекламы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(date) (advertiser_daily_impressions_count{advertiser_id=\"$advertiser_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество кликов рекламы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(date) (advertiser_daily_clicks_count{advertiser_id=\"$advertiser_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Конверсия рекламы по дням (%)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum by(date) (advertiser_daily_conversion{advertiser_id=\"$advertiser_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено на показы рекламы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(date) (advertiser_daily_spent_impressions{advertiser_id=\"$advertiser_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено на клики рекламы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by(date) (advertiser_daily_spent_clicks{advertiser_id=\"$advertiser_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено всего на рекламу по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 41 },
   "targets": [
    {
     "expr": "sum by(date) (advertiser_daily_spent{advertiser_id=\"$advertiser_id\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}