{
 "title": "Статистика рекламных кампаний",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "campaign_id",
    "label": "ID рекламной кампании",
    "query": {
     "query": "label_values(campaign_daily_clicks_count,campaign_id)"
    }
   },
   {
    "name": "campaign_title",
    "query": {
     "query": "label_values(campaign_total_clicks_count{campaign_id=\"$campaign_id\"},campaign_title)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Статистика рекламной кампании $campaign_title",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Количество просмотров",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "campaign_total_impressions_count{campaign_id='$campaign_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество кликов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "campaign_total_clicks_count{campaign_id=\"$campaign_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Конверсия",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "campaign_total_conversion{campaign_id='$campaign_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено на клики",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "campaign_total_spent_clicks{campaign_id='$campaign_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено на просмотры",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "campaign_total_spent_impressions{campaign_id='$campaign_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Всего потрачено",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "campaign_total_spent{campaign_id='$campaign_id'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество просмотров рекламы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(date) (campaign_daily_impressions_count{campaign_id=\"$campaign_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество кликов рекламы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(date) (campaign_daily_clicks_count{campaign_id=\"$campaign_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Конверсия рекламы по дням (%)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum by(date) (campaign_daily_conversion{campaign_id=\"$campaign_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено на показы рекламы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(date) (campaign_daily_spent_impressions{campaign_id=\"$campaign_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено на клики рекламы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by(date) (campaign_daily_spent_clicks{campaign_id=\"$campaign_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потрачено всего на рекламу по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "sum by(date) (campaign_daily_spent{campaign_id=\"$campaign_id\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}