{
 "title": "Серверные метрики",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Использование процессора (система)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_usage",
     "legendFormat": "Использование процессора системой"
    }
   ]
  },
  {
   "title": "Использование процессора (процесс)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "Использование процессора JVM" }
   ]
  },
  {
   "title": "Использование памяти (heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"} / 1024 / 1024)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\"} / 1024 / 1024)",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\"} / 1024 / 1024)",
     "legendFormat": "Commited"
    }
   ]
  },
  {
   "title": "Использование памяти (nonheap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"} / 1024 / 1024)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\"} / 1024 / 1024)",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\"} / 1024 / 1024)",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Активные запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ktor_http_server_requests_active",
     "legendFormat": "Количество активных запросов"
    }
   ]
  },
  {
   "title": "Средняя длительность запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ktor_http_server_requests_seconds)",
     "legendFormat": "Средняя длительность запросов"
    }
   ]
  },
  {
   "title": "Статистика подключений HikariCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "hikaricp_connections", "legendFormat": "Количество подключений" },
    {
     "expr": "hikaricp_connections_max",
     "legendFormat": "Максимальное количество подключений"
    },
    {
     "expr": "hikaricp_connections_min",
     "legendFormat": "Минимальное количество подключений"
    },
    {
     "expr": "hikaricp_connections_idle",
     "legendFormat": "Количество неактивных подключений"
    }
   ]
  },
  {
   "title": "Время подключений HikariCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_sum[5m]) / rate(hikaricp_connections_acquire_seconds_count[5m])",
     "legendFormat": "Среднее время получения подключений из пула"
    },
    {
     "expr": "hikaricp_connections_acquire_seconds_max",
     "legendFormat": "Мксимальное время получения подключений из пула"
    },
    {
     "expr": "rate(hikaricp_connections_creation_seconds_sum[5m]) / rate(hikaricp_connections_creation_seconds_count[5m])",
     "legendFormat": "Среднее время создания подключений"
    },
    {
     "expr": "hikaricp_connections_creation_seconds_max",
     "legendFormat": "Максимальное время создания подключений"
    }
   ]
  }
 ]
}