version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-dev-data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" # необходимо, чтобы можно было получать доступ к бекенду, запущенному на хосте
    ports:
      - '9090:9090'
    volumes:
      - 'prometheus-dev-storage:/prometheus'
      - './prometheus/dev-prometheus.yml:/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-dev-storage:/var/lib/grafana'
volumes:
  db-dev-data:
  grafana-dev-storage:
  prometheus-dev-storage: